//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ageDimension
    {
        public int id { get; set; }
        public Nullable<int> statusCode { get; set; }
        public Nullable<int> UnitsOfMeasurementCode { get; set; }
        public Nullable<double> RecommendedDose { get; set; }
        public Nullable<double> MaxDose { get; set; }
        public Nullable<double> highMissing { get; set; }
    
        public virtual status status { get; set; }
        public virtual ingredient ingredient { get; set; }
    }
}
