//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ingredient()
        {
            this.ingredientsInProes = new HashSet<ingredientsInPro>();
            this.ageDimensions = new HashSet<ageDimension>();
        }
    
        public int id { get; set; }
        public string CDescription { get; set; }
        public Nullable<double> RecommendedDoseMale { get; set; }
        public Nullable<double> RecommendedDoseFemale { get; set; }
        public Nullable<int> UnitCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingredientsInPro> ingredientsInProes { get; set; }
        public virtual UnitsOfMeasurement UnitsOfMeasurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ageDimension> ageDimensions { get; set; }
    }
}
