//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredientsInPro
    {
        public int id { get; set; }
        public Nullable<int> foodID { get; set; }
        public Nullable<int> ingredientsId { get; set; }
        public Nullable<double> countFor100gr { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual Food Food { get; set; }
    }
}
