//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthyMenuEntities : DbContext
    {
        public HealthyMenuEntities()
            : base("name=HealthyMenuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<suitableTo> suitableToes { get; set; }
        public virtual DbSet<foodToMeal> foodToMeals { get; set; }
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<ingredientsInPro> ingredientsInProes { get; set; }
        public virtual DbSet<status> statuses { get; set; }
        public virtual DbSet<UnitsOfMeasurement> UnitsOfMeasurements { get; set; }
        public virtual DbSet<userNutrition> userNutritions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<ageDimension> ageDimensions { get; set; }
    }
}
