//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.userNutritions = new HashSet<userNutrition>();
        }
    
        public int id { get; set; }
        public string userId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string userPassword { get; set; }
        public Nullable<System.DateTime> bornDate { get; set; }
        public string phone { get; set; }
        public Nullable<int> statusCode { get; set; }
        public Nullable<double> myWeight { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<bool> vegetarian { get; set; }
        public Nullable<bool> vegan { get; set; }
    
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userNutrition> userNutritions { get; set; }
    }
}
